### ISSUE TITLE
네비게이션 바 수정

### ISSUE THREAD

**Issue by hj56775** [boostcampwm-2021/iOS04-OwnMyWay#47]
### 작업 목록
 - Back Button 제거
 - home화면으로 pop 버튼

### 예상 시간
 - 1h

**Comment by kimwj9792** [comment]
이거 뭐지 @hj56775 @mandeuk26 @bestowing

**Comment by mandeuk26** [comment]
이거 백버튼이랑 슬라이드 기능 둘다 살리라는거 아닌가요?

**Comment by bestowing** [comment]
저도 그렇게 이해했어요

**Comment by kimwj9792** [comment]
그럼 이거 닫아도 되는거아닌가요?ㅋㅋ

**Comment by mandeuk26** [comment]
맞습니다 닫아버리게씁니다
